import { test, expect } from '@playwright/test';

const artwork = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 100"><g id="ribbon" data-name="Ribbon"><path d="M 30 50 L 550 50" stroke="white" fill="none"/></g></svg>';

async function fourSections(page: any) {
  await page.goto('/#screen=layout');
  await page.evaluate(() => localStorage.clear());
  await page.reload();
  await page.setInputFiles('input[accept=".svg"]', { name: 'ribbon.svg', mimeType: 'image/svg+xml', buffer: Buffer.from(artwork) });
  await page.getByTestId('artwork-create-all-strips').click();
  await page.locator('.la-strip-row').click({ position: { x: 8, y: 8 } });
  await page.getByRole('spinbutton', { name: 'Ribbon LED count' }).fill('41');
  await page.getByRole('spinbutton', { name: 'Ribbon LED count' }).blur();
  await expect(page.getByRole('spinbutton', { name: 'Ribbon LED count' })).toHaveValue('41');
  await page.locator('[data-testid^="divide-toggle-"]').click();
  await page.locator('[data-testid^="divide-sections-"]').fill('4');
  await expect.poll(() => page.locator('[data-testid^="divide-count-"]').evaluateAll((items: HTMLInputElement[]) => items.map(item => item.value)))
    .toEqual(['11', '10', '10', '10']);
  await page.locator('[data-testid^="divide-commit-"]').click();
  await expect(page.locator('.la-strip-row')).toHaveCount(4);
}

test('independent strip keeps its row compact and edits LEDs beside Layout', async ({ page }) => {
  await page.goto('/#screen=layout');
  await page.evaluate(() => localStorage.clear());
  await page.reload();
  await page.getByTestId('layout-primitive-picker').getByRole('button', { name: 'Create line' }).click();
  const row = page.locator('.la-strip-row').first();
  await row.click({ position: { x: 8, y: 8 } });
  const editor = page.locator('.la-strip-detail').first();
  await expect(row.locator('.la-section-miniature, .la-row-count')).toHaveCount(0);
  await expect(row.locator('.layer-name')).not.toHaveCSS('color', 'rgb(255, 255, 255)');
  await expect(row.locator('.la-strip-row-eye')).toBeVisible();
  await expect(row.getByTestId('layout-section-pattern-action')).toBeVisible();
  await expect(editor.locator('.la-strip-settings-head')).toContainText('Layout ·');
  await expect(editor.getByRole('spinbutton', { name: /LED count/ })).toBeVisible();
  await editor.getByRole('spinbutton', { name: /LED count/ }).fill('13');
  await editor.getByRole('spinbutton', { name: /LED count/ }).blur();
  await expect(editor.getByRole('spinbutton', { name: /LED count/ })).toHaveValue('13');
  await page.screenshot({ path: '/tmp/lightweaver-compact-independent-strip.png', fullPage: true });
});

test('one selected editor, direct counts, and no numbered or repeated section navigation', async ({ page }) => {
  await fourSections(page);
  await page.locator('.la-strip-row').nth(1).click({ position: { x: 8, y: 8 } });
  await expect(page.getByTestId('connected-section-editor')).toHaveCount(1);
  await expect(page.getByTestId('connected-child')).toHaveCount(1);
  await page.setViewportSize({ width: 1280, height: 1100 });
  await page.locator('.la-inspector-main').evaluate((element: HTMLElement) => { element.scrollTop = 0; });
  await page.screenshot({ path: '/tmp/lightweaver-selected-editor-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('.la-inspector-main').evaluate((element: HTMLElement) => { element.scrollTop = 0; });
  await page.screenshot({ path: '/tmp/lightweaver-selected-editor-phone.png', fullPage: true });
  await page.locator('.la-strip-row').first().evaluate((element: HTMLElement) => element.scrollIntoView({ block: 'start' }));
  await page.screenshot({ path: '/tmp/lightweaver-selected-editor-phone-strips.png', fullPage: true });
  await expect(page.locator('.lw-connected-bar')).toHaveCount(0);
  await expect(page.locator('.la-wire-n')).toHaveCount(4);
  for (const grip of await page.locator('.la-wire-n').all()) await expect(grip).not.toContainText(/\d/);
  await expect(page.getByRole('spinbutton', { name: 'Ribbon 2 LED count' })).toHaveValue('10');
  await expect(page.getByTestId('connected-boundary')).toHaveCount(0);
  await page.getByRole('spinbutton', { name: 'Ribbon 2 LED count' }).fill('73');
  await page.getByRole('spinbutton', { name: 'Ribbon 2 LED count' }).press('Escape');
  await expect(page.getByRole('spinbutton', { name: 'Ribbon 2 LED count' })).toHaveValue('10');
  await expect(page.getByTestId('layout-total-led-count')).toHaveValue('41');
  await page.getByRole('button', { name: 'One more LED in Ribbon 2' }).click();
  await expect(page.getByRole('spinbutton', { name: 'Ribbon 2 LED count' })).toHaveValue('11');
  await expect(page.getByTestId('layout-total-led-count')).toHaveValue('42');
  await page.getByTitle(/Undo/).first().click();
  await expect(page.getByRole('spinbutton', { name: 'Ribbon 2 LED count' })).toHaveValue('10');
  await page.getByRole('combobox', { name: 'Ribbon shared reel density' }).selectOption('96');
  await expect(page.getByRole('spinbutton', { name: 'Ribbon 2 LED count' })).toHaveValue('10');
  await expect(page.getByRole('combobox', { name: 'Ribbon shared reel density' })).toHaveValue('96');
  await page.getByTitle(/Undo/).first().click();
  await expect(page.getByRole('combobox', { name: 'Ribbon shared reel density' })).toHaveValue('60');
  await page.getByRole('spinbutton', { name: 'Ribbon 2 length in metres' }).fill('0.2');
  await page.getByRole('spinbutton', { name: 'Ribbon 2 length in metres' }).blur();
  await expect(page.getByRole('spinbutton', { name: 'Ribbon 2 LED count' })).toHaveValue('12');
  await page.getByTitle(/Undo/).first().click();
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem('lw_autosave_v3') || '{}').layout?.strips?.length)).toBe(4);
  await page.reload();
  await expect(page.locator('.la-strip-row')).toHaveCount(4);
  await expect(page.getByTestId('layout-total-led-count')).toHaveValue('41');
});

test('Layout pattern gallery previews and applies successive choices until the strip closes it', async ({ page }) => {
  const writes: string[] = [];
  page.on('request', request => {
    if (request.method() === 'POST' && /\/api\/(control|config|project)(?:[/?]|$)/.test(request.url())) writes.push(request.url());
  });
  await fourSections(page);
  const row = page.locator('.la-strip-row').nth(1);
  const trigger = row.getByTestId('layout-section-pattern-action');
  const targetId = await trigger.getAttribute('data-target-id');
  expect(targetId).toBeTruthy();
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem('lw_autosave_v3') || '{}').layout?.strips?.length)).toBe(4);
  await page.goto('/#screen=pattern');
  await expect(page.getByTestId(`section-target-${targetId}`)).toBeVisible();
  await page.getByTestId('look-name').fill('Before Layout edit');
  await page.getByTestId('look-save-preset').click();
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem('lw_autosave_v3') || '{}').devices?.standaloneController?.looks?.some((look: any) => look.label === 'Before Layout edit'))).toBe(true);
  await page.goto('/#screen=layout');
  const firstPatternBefore = await page.locator('.la-strip-row').first().getByTestId('layout-section-pattern-action').innerText();
  const thirdPatternBefore = await page.locator('.la-strip-row').nth(2).getByTestId('layout-section-pattern-action').innerText();
  await trigger.click();
  await expect(page).toHaveURL(/screen=layout/);
  const gallery = page.getByRole('dialog', { name: 'Choose pattern for Ribbon 2' });
  await expect(gallery).toBeVisible();
  await expect(gallery.getByRole('button', { name: 'Plasma', exact: true })).toBeVisible();
  await expect(gallery.locator('.la-pattern-preview').first()).toBeVisible();
  const audition = gallery.getByTestId('layout-pattern-audition');
  await expect(gallery.getByTestId('layout-pattern-audition-canvas')).toBeVisible();
  expect((await gallery.getByTestId('layout-pattern-audition-canvas').boundingBox())?.height).toBeGreaterThanOrEqual(20);
  expect((await gallery.getByTestId('layout-pattern-audition-canvas').boundingBox())?.height).toBeLessThanOrEqual(22);
  await gallery.getByRole('button', { name: 'Fire', exact: true }).focus();
  await expect(audition).toHaveAttribute('aria-label', 'Fire animated preview for Ribbon 2');
  await gallery.getByRole('button', { name: 'Plasma', exact: true }).hover();
  await expect(audition).toHaveAttribute('aria-label', 'Plasma animated preview for Ribbon 2');
  const auditionFrame = () => gallery.getByTestId('layout-pattern-audition-canvas')
    .evaluate((canvas: HTMLCanvasElement) => canvas.toDataURL());
  const firstAuditionFrame = await auditionFrame();
  await expect.poll(auditionFrame).not.toEqual(firstAuditionFrame);
  await gallery.screenshot({ path: '/tmp/lightweaver-layout-pattern-audition.png' });
  await page.keyboard.press('Escape');
  await expect(gallery).toBeHidden();
  await expect(trigger).toBeFocused();
  await expect(row).not.toContainText('Plasma');
  await trigger.click();
  await gallery.getByRole('button', { name: 'Fire', exact: true }).click();
  await expect(gallery).toBeVisible();
  await expect(row).toContainText('Fire');
  await gallery.getByRole('button', { name: 'Plasma', exact: true }).click();
  await expect(gallery).toBeVisible();
  await expect(gallery.getByRole('status')).toContainText('Connect a ready card');
  await expect(audition).toHaveAttribute('aria-label', 'Plasma animated preview for Ribbon 2');
  await expect(row).toContainText('Plasma');
  await expect(page.getByTitle('Toggle ambient light preview (click). Right-click or use ▾ for glow options.')).toHaveClass(/active/);
  const stripId = await row.locator('xpath=..').getAttribute('data-strip-id');
  const ledColors = () => page.locator(`[data-testid^="strip-led-${stripId}-"] circle:first-child`)
    .evaluateAll((dots: SVGCircleElement[]) => dots.map(dot => dot.getAttribute('fill')));
  await expect.poll(async () => new Set(await ledColors()).size).toBeGreaterThan(1);
  const firstFrame = await ledColors();
  await expect.poll(ledColors).not.toEqual(firstFrame);
  await page.screenshot({ path: '/tmp/lightweaver-layout-plasma-on-part.png', fullPage: true });
  await row.locator('.layer-name').click();
  await expect(gallery).toBeHidden();
  await trigger.click();
  await expect(gallery).toBeVisible();
  await gallery.getByRole('button', { name: 'Close pattern gallery' }).click();
  await expect(gallery).toBeHidden();
  await expect(trigger).toBeFocused();
  await trigger.click();
  await expect(gallery).toBeVisible();
  await page.getByTestId(`strip-callout-${stripId}`).click();
  await expect(gallery).toBeHidden();
  await expect(page.locator('.la-strip-row').first().getByTestId('layout-section-pattern-action')).toHaveText(firstPatternBefore);
  await expect(page.locator('.la-strip-row').nth(2).getByTestId('layout-section-pattern-action')).toHaveText(thirdPatternBefore);
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem('lw_autosave_v3') || '{}').layout?.patchBoard?.patches?.map((p: any) => p.playback?.patternId))).toContain('plasma');
  await page.reload();
  await expect(page.locator('.la-strip-row').nth(1)).toContainText('Plasma');
  await page.goto('/#screen=pattern');
  await expect(page.getByTestId(`section-pattern-${targetId}`)).toHaveText('Plasma');
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem('lw_autosave_v3') || '{}').devices?.standaloneController?.looks?.some((look: any) => look.label === 'Before Layout edit'))).toBe(true);
  expect(writes).toEqual([]);
});

test('generated connected sections read as Parts under one physical strip', async ({ page }) => {
  await page.goto('/#screen=layout');
  await page.evaluate(() => localStorage.clear());
  await page.reload();
  await page.getByTestId('layout-primitive-picker').getByRole('button', { name: 'Create line' }).click();
  const parentName = (await page.locator('.la-strip-row .layer-name').innerText()).trim();
  const count = page.locator('.la-strip-detail .la-row-count input');
  await count.fill('41');
  await count.blur();
  await page.locator('[data-testid^="divide-toggle-"]').click();
  await page.locator('[data-testid^="divide-sections-"]').fill('4');
  await page.locator('[data-testid^="divide-commit-"]').click();
  const rows = page.locator('.la-part-row');
  await expect(rows).toHaveCount(4);
  await expect(page.getByTestId('connected-parent')).toHaveCount(1);
  await expect(page.getByTestId('connected-parent')).toContainText(parentName);
  await expect(page.getByTestId('connected-parent')).toContainText('4 parts · 41 LEDs');
  await expect(rows.locator('.layer-name')).toHaveText(['Part 1', 'Part 2', 'Part 3', 'Part 4']);
  await expect(page.locator('.la-strip-family-label')).toHaveCount(0);
  await expect(rows.locator('.la-section-miniature')).toHaveCount(0);
  await expect(page.getByRole('combobox', { name: `${parentName} shared reel density` })).toHaveCount(1);
  await expect(page.getByRole('combobox', { name: `${parentName} shared GPIO output` })).toHaveCount(1);
  await rows.nth(1).click({ position: { x: 8, y: 8 } });
  const partEditor = page.getByRole('region', { name: 'Part 2 settings' });
  await expect(partEditor).toBeVisible();
  await expect(partEditor.getByText('Part 2 settings')).toHaveCount(0);
  await expect(partEditor.getByRole('textbox', { name: 'Part 2 name' })).toHaveCount(0);
  const lengthBox = await partEditor.getByRole('spinbutton', { name: 'Part 2 length in metres' }).boundingBox();
  const gpioBox = await partEditor.getByRole('combobox', { name: 'Part 2 GPIO override' }).boundingBox();
  expect(lengthBox && gpioBox && Math.abs(lengthBox.y - gpioBox.y) < 10 && gpioBox.x > lengthBox.x).toBeTruthy();
  await expect(page.getByTestId('connected-child')).toHaveCount(1);
  const actions = page.getByRole('group', { name: 'Part 2 actions' });
  await expect(actions).toBeVisible();
  await expect(actions.getByRole('button', { name: 'Flip path direction of Part 2' })).toBeDisabled();
  await expect(actions.getByRole('button', { name: 'Edit reflection points of Part 2' })).toBeVisible();
  await expect(actions.getByRole('button', { name: /Move Part 2/ })).toHaveCount(0);
  await expect(actions.getByRole('button', { name: 'Add split inside Part 2' })).toBeVisible();
  await expect(actions.locator('button')).toHaveCount(8);
  await expect(actions.locator('button svg')).toHaveCount(8);
  await page.setViewportSize({ width: 1280, height: 1100 });
  await page.locator('.la-inspector-main').evaluate((element: HTMLElement) => { element.scrollTop = 0; });
  await page.screenshot({ path: '/tmp/lightweaver-parts-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await rows.first().evaluate((element: HTMLElement) => element.scrollIntoView({ block: 'start' }));
  await page.screenshot({ path: '/tmp/lightweaver-parts-phone.png', fullPage: true });
  await actions.screenshot({ path: '/tmp/lightweaver-part-actions-phone.png' });
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem('lw_autosave_v3') || '{}').layout?.strips?.length)).toBe(4);
  const savedIds = await page.evaluate(() => JSON.parse(localStorage.getItem('lw_autosave_v3') || '{}').layout?.sectionFamilies?.[0]?.memberIds);
  await expect(page.getByTestId(`strip-callout-${savedIds[1]}`)).toHaveAttribute('aria-label', /^Part 2 · 10 LEDs$/);
  await page.reload();
  await expect(page.locator('.la-part-row .layer-name')).toHaveText(['Part 1', 'Part 2', 'Part 3', 'Part 4']);
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('lw_autosave_v3') || '{}').layout?.sectionFamilies?.[0]?.memberIds)).toEqual(savedIds);
});

test('duplicating a connected Part is one undoable local edit', async ({ page }) => {
  await page.goto('/#screen=layout');
  await page.evaluate(() => localStorage.clear());
  await page.reload();
  await page.getByTestId('layout-primitive-picker').getByRole('button', { name: 'Create line' }).click();
  const count = page.locator('.la-strip-detail .la-row-count input');
  await count.fill('41');
  await count.blur();
  await page.locator('[data-testid^="divide-toggle-"]').click();
  await page.locator('[data-testid^="divide-sections-"]').fill('4');
  await page.locator('[data-testid^="divide-commit-"]').click();
  await expect(page.locator('.la-part-row')).toHaveCount(4);
  const beforeIds = await page.locator('.la-strip-item').evaluateAll((items: HTMLElement[]) => items.map(item => item.dataset.stripId));
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem('lw_autosave_v3') || '{}').layout?.sectionFamilies?.[0]?.memberIds?.length)).toBe(4);
  const familyBefore = await page.evaluate(() => JSON.parse(localStorage.getItem('lw_autosave_v3') || '{}').layout?.sectionFamilies?.[0]?.memberIds);
  await page.getByRole('group', { name: 'Part 1 actions' }).getByRole('button', { name: 'Duplicate Part 1 as a separate strip' }).click();
  await expect(page.locator('.la-strip-row')).toHaveCount(5);
  await expect(page.getByTestId('layout-total-led-count')).toHaveValue('52');
  await expect(page.locator('.la-strip-row').filter({ hasText: 'copy' })).toHaveCount(1);
  const undo = page.getByTitle(/^Undo \(/);
  await expect(undo).toBeEnabled();
  await undo.focus();
  await page.keyboard.press('Enter');
  await expect(page.locator('.la-strip-row')).toHaveCount(4);
  await expect(page.getByTestId('layout-total-led-count')).toHaveValue('41');
  expect(await page.locator('.la-strip-item').evaluateAll((items: HTMLElement[]) => items.map(item => item.dataset.stripId))).toEqual(beforeIds);
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem('lw_autosave_v3') || '{}').layout?.sectionFamilies?.[0]?.memberIds)).toEqual(familyBefore);
  const redo = page.getByTitle(/^Redo \(/);
  await redo.focus();
  await page.keyboard.press('Enter');
  await expect(page.locator('.la-strip-row')).toHaveCount(5);
  await expect(page.getByTestId('layout-total-led-count')).toHaveValue('52');
});
