/**
 * export.js — serialise pixel maps to WLED / FastLED / CSV formats
 *
 * WLED ledmap.json schema:
 *   { "n": <totalLEDs>, "map": [[x,y], [x,y], ...] }
 *   Upload via WLED web UI → Config → LED Preferences → 2D setup → Custom ledmap
 *
 * Coordinates are in draw order (strip 0 pixel 0, strip 0 pixel 1, ... strip 1 pixel 0, ...)
 */

import { expandPatchBoard } from './patchBoard.js';
import { compileWiring } from './wiringCompiler.js';

/**
 * @typedef {{ x: number, y: number, index: number }} Pixel
 * @typedef {{ normalize?: boolean, scaleX?: number, scaleY?: number, offsetX?: number, offsetY?: number }} ExportOpts
 */

/**
 * @param {Pixel[]} pixels
 * @param {ExportOpts} opts
 * @returns {string}  pretty-printed JSON
 */
export function toWLEDLedmap(pixels, opts = {}) {
  const {
    normalize = true,
    scaleX  = 1, scaleY  = 1,
    offsetX = 0, offsetY = 0,
  } = opts;

  // Sort by index to guarantee order
  const sorted = [...pixels].sort((a, b) => a.index - b.index);
  let coords = sorted.map(px => [px.x, px.y]);

  if (normalize && coords.length > 0) {
    const xs = coords.map(c => c[0]);
    const ys = coords.map(c => c[1]);
    const minX = Math.min(...xs), maxX = Math.max(...xs);
    const minY = Math.min(...ys), maxY = Math.max(...ys);
    const rangeX = maxX - minX || 1; // avoid /0 for collinear vertical/horizontal strips
    const rangeY = maxY - minY || 1;
    coords = coords.map(([x, y]) => [
      (x - minX) / rangeX,
      (y - minY) / rangeY,
    ]);
  }

  const map = coords.map(([x, y]) => [
    r2(x * scaleX + offsetX),
    r2(y * scaleY + offsetY),
  ]);

  return JSON.stringify({ n: pixels.length, map }, null, 2);
}

/**
 * @param {Pixel[]} pixels
 * @param {ExportOpts} opts
 * @returns {string}  C++ header snippet
 */
export function toFastLED(pixels, opts = {}) {
  const data  = JSON.parse(toWLEDLedmap(pixels, opts));
  const lines = data.map.map((pt, i) => `  {${pt[0]}f, ${pt[1]}f},  // LED ${i}`);
  return [
    `// FastLED 2D coordinate map — ${pixels.length} LEDs`,
    `// Generated by Light Weaver`,
    ``,
    `struct Point { float x, y; };`,
    `const Point ledCoords[${pixels.length}] PROGMEM = {`,
    ...lines,
    `};`,
  ].join('\n');
}

/**
 * @param {Pixel[]} pixels
 * @returns {string}  CSV with header row
 */
export function toCSV(pixels) {
  const sorted = [...pixels].sort((a, b) => a.index - b.index);
  const rows   = sorted.map(px => `${px.index},${px.x.toFixed(3)},${px.y.toFixed(3)}`);
  return `index,x,y\n${rows.join('\n')}`;
}

export function pixelsFromStrips(strips = []) {
  const out = [];
  let index = 0;
  for (const strip of strips) {
    for (const px of strip.pixels || []) {
      out.push({
        index,
        stripId: strip.id,
        stripName: strip.name,
        x: px.x,
        y: px.y,
      });
      index++;
    }
  }
  return out;
}

export function pixelsFromPatchBoard(patchBoard, strips = []) {
  return expandPatchBoard(patchBoard, strips).pixels;
}

export function pixelsFromWiring(wiring, strips = [], groups = [], capabilities, options = {}) {
  const compiled = compileWiring({ wiring, strips, groups, symmetry: options.symmetry || null, capabilities });
  if (!compiled.ok) throw new Error(compiled.errors.map(error => error.message).join(' '));
  if (options.requireSendReady === true && compiled.sendReady !== true) {
    throw new Error('Compiled physical wiring is not send-ready; lock and verify every run before export.');
  }
  return compiled.pixels;
}

export function remapFrameToPatchBoard(framePixels = [], patchPixels = [], strips = []) {
  if (!patchPixels.length) return framePixels;
  const offsets = new Map();
  let offset = 0;
  for (const strip of strips) {
    offsets.set(strip.id, offset);
    offset += strip.pixels?.length || strip.pixelCount || 0;
  }
  const black = { r: 0, g: 0, b: 0 };
  return patchPixels.map(pixel => {
    if (pixel.inactive || !pixel.stripId || !Number.isFinite(pixel.sourceLed)) return black;
    const sourceOffset = offsets.get(pixel.stripId);
    if (!Number.isFinite(sourceOffset)) return black;
    return framePixels[sourceOffset + pixel.sourceLed] || black;
  });
}

export function remapFrameToWiring(framePixels = [], compiledWiring, strips = []) {
  return remapFrameToPatchBoard(framePixels, compiledWiring?.pixels || [], strips);
}

export function dmxAddressForPixel(pixelIndex, options = {}) {
  const integer = (value, label, minimum = 0) => {
    const number = Number(value);
    if (!Number.isSafeInteger(number) || number < minimum) {
      throw new RangeError(`${label} must be a safe integer of at least ${minimum}`);
    }
    return number;
  };
  const index = integer(pixelIndex, 'DMX pixel index');
  const startUniverse = integer(options.startUniverse ?? 0, 'DMX start universe');
  const startChannel = integer(options.startChannel ?? 0, 'DMX start channel');
  const channelsPerPixel = integer(options.channelsPerPixel ?? 3, 'DMX channels per pixel', 1);
  const channelsPerUniverse = options.channelsPerUniverse == null
    ? null
    : integer(options.channelsPerUniverse, 'DMX channels per universe', 1);
  const maxUniverse = options.maxUniverse == null
    ? Number.MAX_SAFE_INTEGER
    : integer(options.maxUniverse, 'DMX maximum universe');
  if (startUniverse > maxUniverse) {
    throw new RangeError(`DMX universe ${startUniverse} is outside the 0-${maxUniverse} range`);
  }
  if (channelsPerUniverse != null && startChannel >= channelsPerUniverse) {
    throw new RangeError('DMX start channel must be inside its universe');
  }
  const absoluteChannel = startChannel + index * channelsPerPixel;
  if (!Number.isSafeInteger(absoluteChannel)) {
    throw new RangeError('DMX address exceeds safe integer precision');
  }
  const universe = startUniverse + (channelsPerUniverse == null
    ? 0
    : Math.floor(absoluteChannel / channelsPerUniverse));
  if (!Number.isSafeInteger(universe) || universe > maxUniverse) {
    throw new RangeError(`DMX universe ${universe} is outside the 0-${maxUniverse} range`);
  }
  return {
    universe,
    channel: channelsPerUniverse == null ? absoluteChannel : absoluteChannel % channelsPerUniverse,
  };
}

export function toDmxCsv(frames = []) {
  const rows = ['frame,channel,value'];
  frames.forEach((frame, frameIndex) => {
    frame.forEach((px, i) => {
      const base = dmxAddressForPixel(i, { startChannel: 1, channelsPerUniverse: null }).channel;
      rows.push(`${frameIndex},${base},${px.r}`);
      rows.push(`${frameIndex},${base + 1},${px.g}`);
      rows.push(`${frameIndex},${base + 2},${px.b}`);
    });
  });
  return rows.join('\n');
}

export function toRawFrameDump(frames = []) {
  const bytes = [];
  for (const frame of frames) {
    for (const px of frame) bytes.push(px.r || 0, px.g || 0, px.b || 0);
  }
  return new Uint8Array(bytes);
}

export function makeManifest(project, opts = {}) {
  const strips = project.layout?.strips || [];
  const totalLeds = project.layout?.wiring
    ? pixelsFromWiring(project.layout.wiring, strips, project.layout?.layerGroups).length
    : pixelsFromPatchBoard(project.layout?.patchBoard, strips).length;
  return JSON.stringify({
    app: 'Lightweaver',
    version: project.version,
    project: project.name,
    exportedAt: new Date().toISOString(),
    target: opts.target,
    format: opts.format,
    fps: opts.fps,
    duration: project.show?.duration,
    totalLeds,
    strips: strips.map(s => ({ id: s.id, name: s.name, pixelCount: s.pixels?.length || s.pixelCount || 0 })) || [],
  }, null, 2);
}

/**
 * Trigger a browser file download.
 * @param {string} content
 * @param {string} filename
 * @param {string} mimeType
 */
export function download(content, filename, mimeType = 'application/json') {
  const blob = new Blob([content], { type: mimeType });
  const url  = URL.createObjectURL(blob);
  const a    = Object.assign(document.createElement('a'), { href: url, download: filename });
  a.click();
  URL.revokeObjectURL(url);
}

/** Round to 2 decimal places */
function r2(n) { return Math.round(n * 100) / 100; }

if (import.meta.hot) import.meta.hot.accept();
